### ISSUE TITLE
Interaction between std::max and filesystem.hpp on Windows

### ISSUE THREAD

**Issue by albert-github** [gulrak/filesystem#128]
**Describe the bug**
Interaction between std::max and filesystem.hpp on Windows resulting in a compilation error.

**To Reproduce**
Having the following, small, program:
```
#include <algorithm>
#include <iostream>
#include "filesystem.hpp"

int main(int argc, char **argv)
{
   int x = std::max(42,-5);
   std::cout << x;
}
```
With Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86 we get the error message:
```
cl /EHsc aa.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

aa.cpp
aa.cpp(7): error C2589: '(': illegal token on right side of '::'
aa.cpp(7): error C2062: type 'unknown-type' unexpected
aa.cpp(7): error C2059: syntax error: ')'
```

when removing the line:
```
#include "filesystem.hpp"
```
the program compiles (and functions).

Note:
- when compilig the original program under Cygwin with `g++ (GCC) 10.2.0` I have no problem either.
- placing the `#include "filesystem.hpp"` before the other includes on Windows doesn't help either

**Expected behavior**
Clean compilation (and of course running and working).

**Comment by gulrak** [comment]
This is more or less a similar problem as described in #123.

This behavior is actually documented in the readme: "ℹ️ Be aware, as a header-only library, it is not hiding the fact, that it uses system includes, so they "pollute" your global namespace. Use the forwarding-/implementation-header based approach (see below) to avoid this. For Windows it needs Windows.h and it might be a good idea to define WIN32_LEAN_AND_MEAN or NOMINMAX prior to including filesystem.hpp or fs_std.hpp headers to reduce pollution of your global namespace and compile time. They are not defined by ghc::filesystem to allow combination with contexts where the full Windows.his needed, e.g. for UI elements."

There is no way around this when using `ghc::filesystem` in single-file-header-only mode, as the `Windows.h` header is needed to implement the features. I could set `NOMINMAX` before including it, but as also pointed out in #123, that would also impact other projects using `ghc::filesystem` together with `Windows.h`.

The Cygwin-Variant doesn't have this issue, als there `ghc::filesystem.hpp` uses the POSIX api backend instead of the Windows one, so it doesn't need to include `Windows.h`.
 
So as written in the readme, one way to minimize the effect and avoid the described error is to use:

```cpp
#define NOMINMAX
#define WIN32_LEAN_AND_MEAN // optional
#include "filesystem.hpp"
```

The other one is separate the implementation from the declaration and have a separate CPP file (e.g. `filesystem_impl.cpp`) with:
```cpp
#define GHC_FILESYSTEM_IMPLEMENTATION
#include "filesystem.hpp"
```
and in all files using `ghc::filesystem` use:
```cpp
#define GHC_FILESYSTEM_FWD
#include "filesystem.hpp"
```

Alternatively you could use the additional helper files and just include `fs_fwd.hpp` everywhere and
in just one CPP `fs_impl.hpp`, that uses the same defines described above.
