### ISSUE TITLE
Consider migrating to Catch2 v3

### ISSUE THREAD

**Issue by musicinmybrain** [gulrak/filesystem#165]
**Is your feature request related to a problem? Please describe.**

The Catch2 test framework is now at version 3.x. It would be nice if the tests could be migrated to the current, maintained branch of this framework.

**Describe the solution you'd like**

https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#how-to-migrate-projects-from-v2-to-v3

**Describe alternatives you've considered**

Keep using the current Catch2 2.x until or unless something important breaks.

**Additional context**

**Comment by gulrak** [comment]
Thank you for the suggestion. I'm myself a fan of keeping dependencies up to date, but the main issue is, that this would break compatibility with C++11, and supporting older C++ version was _the_ main reason to actually write this library.

The headline of Catch2 reads: _A modern, C++-native, test framework for unit-tests, TDD and BDD - using C++14, C++17 and later (C++11 support is in v2.x branch, and C++03 on the Catch1.x branch)_ so that would make `ghc::filesystem` enforce C++14 just for the test framework.

**Comment by musicinmybrain** [comment]
Your reasoning makes perfect sense. Thank you for documenting it.
