### ISSUE TITLE
simplified chinese coding error

### ISSUE THREAD

**Issue by nblog** [gulrak/filesystem#83]
**Describe the bug**
coding error

**To Reproduce**
`ghc::filesystem::create_directories("C:\\中文\\downloads");`

![1](https://user-images.githubusercontent.com/10218627/103075103-eb379000-4605-11eb-8a8e-3e911efc4321.png)

**Expected behavior**
support for Simplified Chinese GBK

**Additional context**
maybe it's a mistake when "fromUtf8" converts Chinese GBK

**Comment by gulrak** [comment]
The reason is, that `ghc::filesystem` is written following the ["UTF-8-everywhere" philosophy](https://utf8everywhere.org/), so any `std::string` going in or out is expected to be in UTF-8. There is no handling vor non-unicode Encodings inside of `ghc::filesystem`. On Windows I would expect the code: 

```
ghc::filesystem::create_directories(u8"C:\\中文\\downloads");
```

to create the expected directory name.

I wanted `ghc::filesystem` to not depend on any third party library and portable handling of all non-unicode encodings would introduce a huge amount of code that I would not be able to test in any acceptable way.

I admit that due to some rephrasing in the documentation over the years, it became less clear and the current paragraph in *Differences in API* hints this only quite subtly.

I'll enhance the readme to make this more clear.

**Comment by nblog** [comment]
thanks for your answer.
