### ISSUE TITLE
Implicit String converison not working on Win with v1.5.0

### ISSUE THREAD

**Issue by philbucher** [gulrak/filesystem#94]
**Describe the bug**
I updated to version 1.5.0 and it seems like the implicit conversion from `fs::path` to `std::string` is no longer working on Windows. I think this should be possible, see [cppreference](https://en.cppreference.com/w/cpp/filesystem/path):
`Paths are implicitly convertible to and from std::basic_strings, which makes it possible to use them with over files APIs, e.g. as an argument to std::ifstream::open`

I see you updated some of the documentation for the new version, but I don't fully understand it.

**To Reproduce**
implicitly convert between `fs::path` and `std::string` with MSVC

**Expected behavior**
If I understand correctly, implicit conversion should work also on Windows, as it does on Linux & MacOS

BTW thx for this very cool library, it is super useful when one cannot use newer compilers!

Thx for the help!

**Comment by phprus** [comment]
Hello!

This is not a bug, but a new native-format implementation.

See: https://en.cppreference.com/w/cpp/filesystem/path/native and 
[Changes on v1.5.0](https://github.com/gulrak/filesystem/releases/tag/v1.5.0):
> On Windows wchar_t is now the default for fs::path::value_type and std::wstring is the default für fs::path::string_type.

**Comment by gulrak** [comment]
Yeah, the reason is indeed the change of the default to the more std::filesystem conforming approach to use `std::wstring` as `path::string_type` and the cppreference link you provided explicitly names `std::basic_string` and the **Member types and constants** table specifies: _"`value_type` - character type used by the native encoding of the filesystem: `char` on POSIX, `wchar_t` on Windows"_ and _"`string_type` - `std::basic_string<value_type>`"_ so it is the expected behavior on Windows to implicitly convert to std::wstring only. (The cited `std::ifstream::open` from C++17 would actually not call that implicit conversion, as C++17 gave that method an overload with `const path&` as an argument.)

Pre v1.5.0 the `wchar_t`/`std::wstring` was only used when defining `GHC_WIN_WSTRING_STRING_TYPE`, or using one of the `fs_*.hpp` helper headers. I decided to change the default because I would like to lessen developer-surprise when alternating between `std::filesystem` and `ghc::filesystem` on Windows, even if I found the old default nice for easier multi-platform coding.

If you really want to use `char`/`std::string` you can now select the old api by defining `GHC_WIN_DISABLE_WSTRING_STORAGE_TYPE`.

**Note:** Be aware that the implicitly converted `std::string` of such  `path` given to an `std::ifstream` on Windows will not be able to open files with special unicode characters like german umlauts (äöü) as the non-wchar file api of Windows falls back to 8-bit users-locale encoding, so no UTF-8 support, while MSVC extended `std::ifstream` to also accept `std::wstring` as a filename (and so the implicit `std::wstring` conversion of v1.5.0 should work with file streams on MSVC and allow opening files with Unicode characters in their filename).

**Comment by philbucher** [comment]
awesome thx for the explanations!
